### ISSUE TITLE
Upgrade to use TensorFlow 2

### ISSUE THREAD

**Issue by mommi84** [LiberAI/NSpM#38]
Replace the `./nmt/` submodule with an internal library based on the [NMT with attention](https://www.tensorflow.org/tutorials/text/nmt_with_attention) tutorial compatible with TensorFlow 2.2.0rc4.

**Comment by anatta8** [comment]
I am looking forward on this too, I am having so much trouble installing Tensorflow 1 . If anyone can help upgrade this will be so helpful.

**Comment by mommi84** [comment]
Solved in PR #50.
