### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by MikeyBeez** [LiberAI/NSpM#55]
unzip art_30.zip
Archive:  art_30.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of art_30.zip or
        art_30.zip.zip, and cannot find art_30.zip.ZIP, period.

**Comment by mommi84** [comment]
Thanks for reporting this. It was missed during the migration of large files from git-lfs to AWS.

Please use this link: https://nspm-models.s3.eu-west-2.amazonaws.com/v2/art_30.zip

**Comment by MikeyBeez** [comment]
Thanks.  Cheers! :)
